"""End-to-end integration tests for the full MicroAgent pipeline.

All tests use synthetic data generated by microagent.demo.synthetic and
run without real microscopy images or GPU access.

Run with:
    uv run pytest tests/integration/ -m integration -v
"""

from __future__ import annotations

from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _f1_at_05(eval_result) -> float:
    """Return the dataset-level F1 at IoU=0.5 threshold."""
    for tm in eval_result.summary.per_threshold:
        if abs(tm.threshold - 0.5) < 1e-9:
            return tm.f1
    return eval_result.summary.per_threshold[0].f1


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_full_pipeline_synthetic(tmp_path, synthetic_data):
    """Full pipeline: generate → inspect → segment → evaluate → report.

    Verifies:
    - HTML report is produced
    - Dataset-level F1 at IoU=0.5 is > 0.5 (reasonable quality)
    - No crashes throughout
    """
    from microagent.core.evaluate import evaluate_masks
    from microagent.core.inspect import inspect_directory
    from microagent.core.segment import run_segmentation
    from microagent.viz.report import generate_report, load_report_data

    base, image_dir, gt_dir = synthetic_data
    project_yaml = base / "project.yaml"

    # 1. Inspect -----------------------------------------------------------
    insp = inspect_directory(image_dir)
    assert insp.file_count == 5
    assert not any(issue.startswith("Failed") for issue in insp.issues), (
        f"Unexpected load failures: {insp.issues}"
    )
    insp_json = tmp_path / "inspection.json"
    insp.save_json(insp_json)

    # 2. Segment -----------------------------------------------------------
    masks_dir = tmp_path / "masks"
    masks_dir.mkdir()
    seg = run_segmentation(
        image_dir=image_dir,
        output_dir=masks_dir,
        model="cellpose",
        project_path=project_yaml if project_yaml.exists() else None,
    )
    assert len(seg.mask_paths) == 5
    assert all(Path(p).exists() for p in seg.mask_paths)
    seg_json = tmp_path / "segmentation.json"
    seg.save_json(seg_json)

    # 3. Evaluate ----------------------------------------------------------
    ev = evaluate_masks(
        pred_dir=masks_dir,
        gt_dir=gt_dir,
        thresholds=[0.5, 0.75],
        force_fallback=True,  # avoid optional stardist dependency
    )
    assert ev.summary.n_images == 5
    assert len(ev.unmatched_preds) == 0, (
        f"Unmatched predictions: {ev.unmatched_preds}"
    )
    f1 = _f1_at_05(ev)
    assert f1 > 0.5, (
        f"F1@0.5={f1:.3f} is too low — check synthetic data quality or "
        "CellPose diameter settings in project.yaml"
    )
    ev_json = tmp_path / "metrics.json"
    ev.save_json(ev_json)

    # 4. Report ------------------------------------------------------------
    report_path = tmp_path / "report.html"
    data = load_report_data(
        inspection_json=insp_json,
        segmentation_json=seg_json,
        evaluation_json=ev_json,
        project_yaml=project_yaml if project_yaml.exists() else None,
        command="integration_test_full_pipeline",
    )
    out = generate_report(data, report_path)

    assert out == report_path
    assert report_path.exists()
    html = report_path.read_text(encoding="utf-8")
    assert len(html) > 500, "Report HTML seems too short"
    assert "microagent" in html.lower(), "Report should mention microagent"


@pytest.mark.integration
def test_pipeline_no_ground_truth(tmp_path, synthetic_data):
    """Pipeline without evaluation step: generate → inspect → segment → report.

    Verifies:
    - Report is generated without an evaluation section (no crashes)
    - Segmentation still runs and produces masks
    """
    from microagent.core.inspect import inspect_directory
    from microagent.core.segment import run_segmentation
    from microagent.viz.report import generate_report, load_report_data

    base, image_dir, _gt_dir = synthetic_data
    project_yaml = base / "project.yaml"

    # Inspect
    insp = inspect_directory(image_dir)
    insp_json = tmp_path / "inspection.json"
    insp.save_json(insp_json)

    # Segment
    masks_dir = tmp_path / "masks"
    masks_dir.mkdir()
    seg = run_segmentation(
        image_dir=image_dir,
        output_dir=masks_dir,
        model="cellpose",
        project_path=project_yaml if project_yaml.exists() else None,
    )
    seg_json = tmp_path / "segmentation.json"
    seg.save_json(seg_json)

    # Report without evaluation
    report_path = tmp_path / "report.html"
    data = load_report_data(
        inspection_json=insp_json,
        segmentation_json=seg_json,
        evaluation_json=None,  # explicitly omit
        project_yaml=project_yaml if project_yaml.exists() else None,
        command="integration_test_no_gt",
    )
    generate_report(data, report_path)

    assert report_path.exists()
    html = report_path.read_text(encoding="utf-8")
    assert len(html) > 500

    # Evaluation section should be absent or empty
    assert data.evaluation is None


@pytest.mark.integration
def test_pipeline_with_optimization(tmp_path, synthetic_data):
    """Pipeline with hyperparameter optimization.

    Verifies:
    - 3 optimization trials run without crashing
    - Best params are returned
    - Segmentation with best params produces valid masks
    - Evaluation runs successfully

    Skipped if optuna is not installed (tracking extra).
    """
    pytest.importorskip("optuna")

    from microagent.core.evaluate import evaluate_masks
    from microagent.core.optimize import OptimizeConfig, run_optimization
    from microagent.core.segment import run_segmentation

    base, image_dir, gt_dir = synthetic_data

    # Run optimization with just 3 trials for speed
    config = OptimizeConfig(
        image_dir=image_dir,
        gt_dir=gt_dir,
        model="cellpose",
        n_trials=3,
        metric="f1",
        iou_threshold=0.5,
        seed=42,
        project_path=base / "project.yaml" if (base / "project.yaml").exists() else None,
    )
    opt_result = run_optimization(config)

    assert len(opt_result.trials) == 3
    assert 0.0 <= opt_result.best_value <= 1.0
    assert 0.0 <= opt_result.baseline_value <= 1.0
    assert "diameter" in opt_result.best_params or "flow_threshold" in opt_result.best_params

    # Segment with optimised parameters
    masks_dir = tmp_path / "masks_optimized"
    masks_dir.mkdir()
    seg = run_segmentation(
        image_dir=image_dir,
        output_dir=masks_dir,
        model="cellpose",
        **opt_result.best_params,
    )
    assert len(seg.mask_paths) == 5

    # Evaluate
    ev = evaluate_masks(
        pred_dir=masks_dir,
        gt_dir=gt_dir,
        thresholds=[0.5],
        force_fallback=True,
    )
    assert ev.summary.n_images == 5
    # Best params should achieve at least some positive F1
    assert _f1_at_05(ev) >= 0.0


@pytest.mark.integration
def test_provenance_tracking(tmp_path, synthetic_data):
    """Verify that experiments.jsonl captures provenance for each pipeline step.

    Verifies:
    - experiments.jsonl is created
    - Each logged run has run_id, metadata, and results
    - Metadata includes microagent_version and timestamp_utc
    - Two runs can be retrieved and compared
    """
    from microagent.core.inspect import inspect_directory
    from microagent.core.segment import run_segmentation
    from microagent.fair.tracking import ExperimentTracker, tracked_run

    base, image_dir, _gt_dir = synthetic_data
    project_yaml = base / "project.yaml"

    tracker = ExperimentTracker(tmp_path / "experiments.jsonl")

    # Log inspect step
    inspect_params = {"path": str(image_dir)}
    with tracked_run(tracker, "microagent inspect", inspect_params, image_dir) as results:
        insp = inspect_directory(image_dir)
        results["file_count"] = insp.file_count
        results["channel_count"] = insp.channel_count

    # Log segment step
    masks_dir = tmp_path / "masks"
    masks_dir.mkdir()
    with tracked_run(
        tracker,
        "microagent segment",
        {"model": "cellpose", "project": str(project_yaml)},
        image_dir,
    ) as results:
        seg = run_segmentation(
            image_dir=image_dir,
            output_dir=masks_dir,
            model="cellpose",
            project_path=project_yaml if project_yaml.exists() else None,
        )
        results["n_masks"] = len(seg.mask_paths)
        results["total_cells"] = sum(s.n_labels for s in seg.per_image_stats)

    # Verify the JSONL file
    assert tracker.path.exists()
    runs = tracker.list_runs()
    assert len(runs) >= 2, f"Expected ≥2 logged runs, got {len(runs)}"

    for run in runs:
        assert "run_id" in run, "Each run must have a run_id"
        assert "metadata" in run, "Each run must have metadata"
        assert "results" in run, "Each run must have results"
        meta = run["metadata"]
        assert "microagent_version" in meta
        assert "timestamp_utc" in meta
        assert "python_version" in meta

    # Verify individual retrieval works
    run_ids = [r["run_id"] for r in runs[-2:]]
    r0 = tracker.get_run(run_ids[0])
    assert r0["run_id"] == run_ids[0]

    # Verify run-comparison diff
    diff = tracker.compare_runs(run_ids[0], run_ids[1])
    assert isinstance(diff, dict)  # may be empty if identical metadata

    # Verify results were captured
    inspect_run = next(r for r in runs if "file_count" in r.get("results", {}))
    assert inspect_run["results"]["file_count"] == 5

    segment_run = next(r for r in runs if "n_masks" in r.get("results", {}))
    assert segment_run["results"]["n_masks"] == 5


@pytest.mark.integration
def test_mcp_pipeline(tmp_path, synthetic_data, monkeypatch):
    """Call MCP tools programmatically in sequence and verify JSON responses.

    Verifies:
    - Each MCP tool returns {"status": "success", ...}
    - inspect_data, segment, evaluate, generate_report tools work end-to-end
    - generate_report discovers JSON files from the working directory

    Skipped if the mcp package is not installed.
    """
    pytest.importorskip("mcp")

    # mcp_server raises ImportError at module level if mcp is absent
    import microagent.mcp_server as mcp_mod

    base, image_dir, gt_dir = synthetic_data

    # Prepare output paths inside tmp_path
    masks_dir = tmp_path / "masks"
    masks_dir.mkdir()

    # 1. Inspect via MCP ---------------------------------------------------
    result = mcp_mod.inspect_data(str(image_dir))
    assert result["status"] == "success", f"inspect_data failed: {result}"
    assert result["file_count"] == 5

    # 2. Segment via MCP ---------------------------------------------------
    result = mcp_mod.segment(
        image_dir=str(image_dir),
        output_dir=str(masks_dir),
        model="cellpose",
    )
    assert result["status"] == "success", f"segment failed: {result}"
    assert len(result["mask_paths"]) == 5

    # 3. Evaluate via MCP --------------------------------------------------
    result = mcp_mod.evaluate(
        pred_dir=str(masks_dir),
        gt_dir=str(gt_dir),
        thresholds="0.5",
    )
    assert result["status"] == "success", f"evaluate failed: {result}"
    assert result["summary"]["n_images"] == 5

    # 4. Prepare JSON files for generate_report (it uses cwd discovery) ----
    # Write inspection and segmentation JSON to tmp_path
    from microagent.core.inspect import inspect_directory
    from microagent.core.segment import run_segmentation

    insp = inspect_directory(image_dir)
    insp.save_json(tmp_path / "inspection.json")

    seg = run_segmentation(image_dir, masks_dir, model="cellpose")
    seg.save_json(tmp_path / "segmentation.json")

    # Change cwd so generate_report can auto-discover files
    monkeypatch.chdir(tmp_path)

    result = mcp_mod.generate_report(output=str(tmp_path / "report.html"))
    assert result["status"] == "success", f"generate_report failed: {result}"

    report_path = Path(result["report_path"])
    assert report_path.exists()
    html = report_path.read_text(encoding="utf-8")
    assert len(html) > 500
