"""Container and reproducibility export utilities for FAIR compliance."""

from __future__ import annotations

import importlib.metadata
import json
import platform
import subprocess
import sys
import zipfile
from pathlib import Path
from textwrap import dedent

from microagent.fair.provenance import RunMetadata

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _pip_freeze() -> list[str]:
    """Return lines from ``pip freeze`` (or importlib fallback)."""
    try:
        result = subprocess.check_output(
            [sys.executable, "-m", "pip", "freeze"],
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return [line for line in result.splitlines() if line and not line.startswith("#")]
    except Exception:
        # Fallback: enumerate installed distributions
        dists = importlib.metadata.packages_distributions()
        seen: set[str] = set()
        lines: list[str] = []
        for pkg in sorted(dists):
            try:
                ver = importlib.metadata.version(pkg)
                entry = f"{pkg}=={ver}"
                if entry not in seen:
                    seen.add(entry)
                    lines.append(entry)
            except Exception:
                pass
        return lines


def _cuda_base_image(cuda_version: str | None) -> str:
    """Choose the best matching CUDA base image tag."""
    if cuda_version is None:
        return "python:3.11-slim"
    # Map CUDA X.Y → nvidia/cuda:X.Y.z-runtime-ubuntu22.04
    # We only pin the major.minor and use a widely available patch.
    major_minor = ".".join(cuda_version.split(".")[:2])
    known = {
        "12.1": "12.1.0",
        "12.2": "12.2.0",
        "12.3": "12.3.0",
        "11.8": "11.8.0",
        "11.7": "11.7.1",
    }
    patch = known.get(major_minor, f"{major_minor}.0")
    return f"nvidia/cuda:{patch}-runtime-ubuntu22.04"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_dockerfile(provenance: RunMetadata, output_path: Path) -> Path:
    """Generate a Dockerfile that reproduces the current environment.

    Parameters
    ----------
    provenance:
        Run metadata collected by :func:`microagent.fair.provenance.collect_metadata`.
    output_path:
        Destination path for the generated ``Dockerfile``.

    Returns
    -------
    Path
        The path that was written (same as *output_path*).
    """
    use_gpu = provenance.cuda_version is not None
    runtime_base = _cuda_base_image(provenance.cuda_version) if use_gpu else "python:3.11-slim"
    py_ver = provenance.python_version  # e.g. "3.11.7"
    ma_ver = provenance.microagent_version

    git_label = provenance.git_commit or "unknown"

    lines = [
        "# syntax=docker/dockerfile:1",
        f"# Generated by MicroAgent {ma_ver} — git {git_label}",
        "",
        "# ── Stage 1: builder ─────────────────────────────────────────────────",
        "FROM python:3.11-slim AS builder",
        "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "    build-essential curl git && \\",
        "    rm -rf /var/lib/apt/lists/*",
        "",
        "# Install uv",
        "RUN pip install --no-cache-dir uv",
        "",
        "WORKDIR /build",
        "COPY pyproject.toml ./",
        "COPY src/ ./src/",
        "",
        "# Install project + all optional deps into /opt/venv",
        "RUN uv venv /opt/venv && \\",
        "    . /opt/venv/bin/activate && \\",
        "    uv pip install --no-cache '.[all]'",
        "",
        "# ── Stage 2: runtime ─────────────────────────────────────────────────",
        f"FROM {runtime_base} AS runtime",
        "",
        "LABEL maintainer='MicroAgent Contributors'",
        f"LABEL version='{ma_ver}'",
        "LABEL description='Agentic microscopy image analysis tool'",
        "LABEL license='Apache-2.0'",
        f"LABEL python.version='{py_ver}'",
    ]

    if use_gpu:
        lines.append(f"LABEL cuda.version='{provenance.cuda_version}'")
        if provenance.gpu_name:
            lines.append(f"LABEL gpu.tested='{provenance.gpu_name}'")

    if provenance.git_commit:
        lines.append(f"LABEL vcs.ref='{provenance.git_commit}'")

    lines += [
        "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "    libgomp1 libglib2.0-0 libsm6 libxrender1 libxext6 && \\",
        "    rm -rf /var/lib/apt/lists/*",
        "",
        "COPY --from=builder /opt/venv /opt/venv",
        "COPY src/ /app/src/",
        "",
        "ENV PATH='/opt/venv/bin:$PATH'",
        "ENV PYTHONUNBUFFERED=1",
        "ENV MPLBACKEND=Agg",
        "",
        "WORKDIR /data",
        "",
        "ENTRYPOINT ['microagent']",
        "CMD ['--help']",
    ]

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def generate_apptainer_def(provenance: RunMetadata, output_path: Path) -> Path:
    """Generate an Apptainer/Singularity definition file for HPC environments.

    No root access required to build or run the resulting image.

    Parameters
    ----------
    provenance:
        Run metadata from :func:`microagent.fair.provenance.collect_metadata`.
    output_path:
        Destination path for the ``.def`` file.

    Returns
    -------
    Path
        The path that was written.
    """
    use_gpu = provenance.cuda_version is not None
    ma_ver = provenance.microagent_version
    py_ver = provenance.python_version
    git_label = provenance.git_commit or "unknown"

    if use_gpu:
        bootstrap = "docker"
        from_ = _cuda_base_image(provenance.cuda_version)
    else:
        bootstrap = "docker"
        from_ = "python:3.11-slim"

    content = dedent(f"""\
        # Apptainer/Singularity definition generated by MicroAgent {ma_ver}
        # git commit: {git_label}
        # No root required to build: apptainer build --fakeroot microagent.sif microagent.def
        # Run: apptainer run microagent.sif --help

        Bootstrap: {bootstrap}
        From: {from_}

        %labels
            Author MicroAgent Contributors
            Version {ma_ver}
            PythonVersion {py_ver}
            License Apache-2.0
            GitCommit {git_label}
            {"CUDAVersion " + (provenance.cuda_version or "none")}

        %environment
            export PATH=/opt/venv/bin:$PATH
            export PYTHONUNBUFFERED=1
            export MPLBACKEND=Agg
            {"export NVIDIA_VISIBLE_DEVICES=all" if use_gpu else ""}
            {"export NVIDIA_DRIVER_CAPABILITIES=compute,utility" if use_gpu else ""}

        %post
            apt-get update && apt-get install -y --no-install-recommends \\
                build-essential curl git libgomp1 libglib2.0-0 && \\
            rm -rf /var/lib/apt/lists/*

            pip install --no-cache-dir uv
            uv venv /opt/venv
            . /opt/venv/bin/activate
            uv pip install --no-cache 'microagent[all]=={ma_ver}' || \\
                uv pip install --no-cache '.[all]'

        %runscript
            exec microagent "$@"

        %help
            MicroAgent {ma_ver} — agentic microscopy image analysis.
            Usage: apptainer run microagent.sif [command] [options]
            For GPU support: apptainer run --nv microagent.sif [command]
    """)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def generate_environment_lock(output_path: Path) -> Path:
    """Export a complete environment lockfile with Python and system info.

    Parameters
    ----------
    output_path:
        Destination path for the lockfile (text format).

    Returns
    -------
    Path
        The path that was written.
    """
    py = sys.version_info
    python_ver = f"{py.major}.{py.minor}.{py.micro}"

    cuda_ver: str | None = None
    try:
        import torch

        if torch.cuda.is_available():
            cuda_ver = torch.version.cuda
    except ImportError:
        pass

    from datetime import datetime, timezone

    now_utc = datetime.now(timezone.utc).isoformat()

    sections: list[str] = [
        "# MicroAgent Environment Lock",
        f"# Generated: {now_utc}",
        "",
        "# === System Info ===",
        f"# OS: {platform.platform()}",
        f"# Python: {python_ver}",
        f"# CUDA: {cuda_ver or 'none'}",
        f"# Architecture: {platform.machine()}",
        "",
        "# === Python Packages (pip freeze) ===",
    ]
    sections.extend(_pip_freeze())

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(sections) + "\n", encoding="utf-8")
    return output_path


def export_reproducibility_bundle(
    run_id: str,
    output_dir: Path,
    experiments_path: Path = Path("experiments.jsonl"),
    project_yaml: Path | None = None,
) -> Path:
    """Create a self-contained reproducibility bundle for a specific run.

    The bundle is a zip archive containing:

    * ``Dockerfile`` — pinned to the exact run environment
    * ``requirements.txt`` — pinned pip freeze
    * ``run_metadata.json`` — provenance metadata
    * ``experiments.jsonl`` — the specific run entry
    * ``project.yaml`` — if found at *project_yaml* or ``./project.yaml``
    * ``README.md`` — step-by-step reproduction instructions

    Parameters
    ----------
    run_id:
        8-character run identifier from :class:`~microagent.fair.tracking.ExperimentTracker`.
    output_dir:
        Directory where the ``.zip`` will be written.
    experiments_path:
        Path to the ``experiments.jsonl`` log file.
    project_yaml:
        Path to ``project.yaml``; auto-detected if ``None``.

    Returns
    -------
    Path
        Path to the written ``.zip`` file.

    Raises
    ------
    KeyError
        If *run_id* is not found in the experiments log.
    FileNotFoundError
        If *experiments_path* does not exist.
    """
    from microagent.fair.provenance import RunMetadata

    experiments_path = Path(experiments_path)
    if not experiments_path.exists():
        raise FileNotFoundError(f"Experiments log not found: {experiments_path}")

    # Load the specific run record
    run_record: dict | None = None
    with experiments_path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            if record.get("run_id") == run_id:
                run_record = record
                break

    if run_record is None:
        raise KeyError(f"Run '{run_id}' not found in {experiments_path}")

    meta_dict = run_record.get("metadata", {})
    provenance = RunMetadata(
        microagent_version=meta_dict.get("microagent_version", "unknown"),
        python_version=meta_dict.get("python_version", "unknown"),
        platform=meta_dict.get("platform", "unknown"),
        cellpose_version=meta_dict.get("cellpose_version"),
        stardist_version=meta_dict.get("stardist_version"),
        torch_version=meta_dict.get("torch_version", "unknown"),
        numpy_version=meta_dict.get("numpy_version", "unknown"),
        cuda_version=meta_dict.get("cuda_version"),
        gpu_name=meta_dict.get("gpu_name"),
        gpu_vram_mb=meta_dict.get("gpu_vram_mb"),
        cpu_model=meta_dict.get("cpu_model", "unknown"),
        ram_total_gb=meta_dict.get("ram_total_gb", 0.0),
        data_hash=meta_dict.get("data_hash", ""),
        parameters=meta_dict.get("parameters", {}),
        random_seed=meta_dict.get("random_seed", 0),
        timestamp_utc=meta_dict.get("timestamp_utc", ""),
        wall_clock_seconds=meta_dict.get("wall_clock_seconds", 0.0),
        git_commit=meta_dict.get("git_commit"),
        git_dirty=meta_dict.get("git_dirty"),
        command=meta_dict.get("command", ""),
    )

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        # 1. Dockerfile
        dockerfile_path = tmp_path / "Dockerfile"
        generate_dockerfile(provenance, dockerfile_path)

        # 2. requirements.txt (current env, with header explaining pinning)
        req_path = tmp_path / "requirements.txt"
        generate_environment_lock(req_path)

        # 3. run_metadata.json
        meta_path = tmp_path / "run_metadata.json"
        meta_path.write_text(
            json.dumps(run_record, indent=2, default=str), encoding="utf-8"
        )

        # 4. experiments.jsonl (single run entry only)
        exp_path = tmp_path / "experiments.jsonl"
        exp_path.write_text(
            json.dumps(run_record, default=str) + "\n", encoding="utf-8"
        )

        # 5. project.yaml (if available)
        resolved_yaml: Path | None = project_yaml
        if resolved_yaml is None:
            candidate = Path("project.yaml")
            if candidate.exists():
                resolved_yaml = candidate
        if resolved_yaml and resolved_yaml.exists():
            (tmp_path / "project.yaml").write_bytes(resolved_yaml.read_bytes())

        # 6. README.md
        gpu_flag = "--gpus all \\\n    " if provenance.cuda_version else ""
        readme = dedent(f"""\
            # MicroAgent Reproducibility Bundle — run `{run_id}`

            Generated by MicroAgent {provenance.microagent_version}
            Run timestamp: {provenance.timestamp_utc}
            Original command: `{provenance.command}`

            ## Environment

            | Key | Value |
            |-----|-------|
            | Python | {provenance.python_version} |
            | CUDA | {provenance.cuda_version or "none (CPU run)"} |
            | GPU | {provenance.gpu_name or "none"} |
            | Platform | {provenance.platform} |
            | Git commit | {provenance.git_commit or "unknown"} |

            ## Reproduce with Docker

            ```bash
            docker build -t microagent-{run_id} .
            docker run --rm \\
                {gpu_flag}-v $(pwd)/data:/data \\
                microagent-{run_id} \\
                {provenance.command}
            ```

            ## Reproduce with Apptainer (HPC)

            ```bash
            apptainer build --fakeroot microagent.sif microagent.def
            apptainer run {"--nv " if provenance.cuda_version else ""}\\
                --bind $(pwd)/data:/data \\
                microagent.sif \\
                {provenance.command}
            ```

            ## Manual reproduction

            ```bash
            python -m venv .venv && source .venv/bin/activate
            pip install -r requirements.txt
            {provenance.command}
            ```

            ## Data integrity

            Input data SHA-256: `{provenance.data_hash or "not recorded"}`
        """)
        (tmp_path / "README.md").write_text(readme, encoding="utf-8")

        # Zip everything
        zip_path = output_dir / f"{run_id}_reproducibility.zip"
        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for f in sorted(tmp_path.rglob("*")):
                if f.is_file():
                    zf.write(f, f.relative_to(tmp_path))

    return zip_path
